name: first workflow
on: workflow_dispatch
jobs:
  first-jobs:
    run-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hellow World!"
      - name: print goodbye
        run: echo " Done - bye!" 
      
    
                  
